CREATE DATABASE IF NOT EXISTS `DATABASE`;
USE `DATABASE`;

CREATE TABLE IF NOT EXISTS User(
   username VARCHAR(25),
   password VARCHAR(50),
   PRIMARY KEY(username)
);

CREATE TABLE IF NOT EXISTS Room(
   id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   name VARCHAR(50),
   mode INT,
   password VARCHAR(50),
   owner VARCHAR(25) NOT NULL,
   FOREIGN KEY(owner) REFERENCES User(username)
);

CREATE TABLE IF NOT EXISTS Story(
   id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   name VARCHAR(50),
   description VARCHAR(300),
   value INT,
   roomId INT NOT NULL,
   FOREIGN KEY(roomId) REFERENCES Room(id)
);